base_url = "https://onlyrats.online/"

title = "OnlyRats"
description = "Only the hottest rats around"
author = "Levi Akatsuki (https://f-list.net/c/3A Levi)"

# Build options
build_search_index = false
compile_sass = true

# Generation options
generate_feeds = false

# Tags system
taxonomies = []

[markdown]
# Rendering
highlight_code = true
render_emoji = true

# External links
external_links_target_blank = true
external_links_no_referrer = true
external_links_no_follow = true

# Image loading
lazy_async_image = true

[extra]
theme = "jane"
